(() => {
  'use strict';
  const $ = (s, p=document) => p.querySelector(s);
  const $$ = (s, p=document) => [...p.querySelectorAll(s)];
  const getNum = (k,d=0) => { const v = Number(localStorage.getItem(k)); return Number.isFinite(v)?v:d; };
  const setNum = (k,v) => { try { localStorage.setItem(k,String(v)); } catch(_){} };

  const PROJECTS = {
    waid: {
      kicker:'APPLICATION DEVELOPMENT · 2026', title:'Course Enrolment Web App',
      desc:'A working web application that turns course-enrolment business rules into interactive application logic. Students can log in, browse courses, enrol or drop courses, and receive feedback when prerequisites, timetable clashes or approval rules affect an enrolment.',
      evidence:[['WHAT I BUILT','Login, course browsing, enrol/drop actions and status feedback'],['BUSINESS LOGIC','Prerequisites, timetable clashes, approval-required enrolments and course limits'],['DATA','External course/student JSON with fallback sample data'],['TOOLS','HTML, CSS, Vue.js, Python through Brython']],
      tags:['HTML','CSS','VUE.JS','PYTHON / BRYTHON','JSON'],
      actions:[['View live app ↗','https://vtxzenyx.github.io/course-enrolment-web-app/','primary'],['View GitHub ↗','https://github.com/VTXZenyx/course-enrolment-web-app','ghost']]
    },
    sql: {
      kicker:'SQL · SQLITE · DATABASE DESIGN', title:'SQL & Relational Database Portfolio',
      desc:'A curated portfolio of my real university database work, organised by topic. It includes query files, the SQLite music database I used, database-design evidence and screenshots from DB Browser for SQLite.',
      evidence:[['QUERYING','Filtering, multi-table joins, GROUP BY/HAVING and aggregate analysis'],['MORE ADVANCED SQL','Nested and correlated subqueries, self joins and date/time functions'],['DATABASE DESIGN','Functional dependencies, normalisation, PK/FK and composite keys'],['OPERATIONS','DDL/DML, transactions, ACID concepts and SQL views'],['TOOLING','SQLite, DB Browser for SQLite and Draw.io']],
      tags:['SQL','SQLITE','DB BROWSER','SUBQUERIES','NORMALISATION','TRANSACTIONS'],
      actions:[['View SQL project ↗','https://github.com/VTXZenyx/sql-database-portfolio','primary']]
    },
    netflix:{kicker:'DATA ANALYSIS',title:'Netflix Data Analysis',desc:'Python analysis of a dataset containing more than 8,000 Netflix titles. I used the project to practise cleaning, exploring and visualising data and turning observations into a clearer story.',evidence:[['DATASET','8,000+ Netflix titles'],['TOOLS','Python, Pandas, NumPy and Matplotlib'],['FOCUS','Exploration, patterns, summaries and visual communication']],tags:['PYTHON','PANDAS','NUMPY','MATPLOTLIB'],actions:[]},
    r:{kicker:'R / RSTUDIO',title:'R Data Analysis & Programming',desc:'Coursework and practice using R for data structures, filtering, functions, grouped analysis and programming fundamentals.',evidence:[['TOOLS','R and RStudio'],['PRACTICE','Vectors, lists, filtering, loops and functions'],['ANALYSIS','apply/lapply/sapply, tapply, grep/grepl and grouped work']],tags:['R','RSTUDIO','DATA'],actions:[]},
    systems:{kicker:'INFORMATION SYSTEMS',title:'Systems Thinking & Stakeholder Analysis',desc:'Systems and business-analysis work where I mapped stakeholders, relationships, system boundaries, feedback loops and trade-offs before jumping to solutions.',evidence:[['FOCUS','People, processes, technology and system context'],['METHODS','Stakeholder analysis, systems thinking and problem framing'],['GOAL','Understand the problem clearly before designing a response']],tags:['STAKEHOLDERS','SYSTEMS','PROBLEM FRAMING'],actions:[]}
  };

  function initClock(){
    const c=$('#clock'), y=$('#year'); if(y)y.textContent=new Date().getFullYear();
    const tick=()=>{ if(!c)return; try{ c.textContent=new Intl.DateTimeFormat('en-NZ',{timeZone:'Pacific/Auckland',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()); }catch{ c.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); }}; tick(); setInterval(tick,30000);
  }
  function initCursor(){ const h=$('.cursor-halo'); if(!h)return; window.addEventListener('pointermove',e=>{h.style.left=e.clientX+'px';h.style.top=e.clientY+'px';},{passive:true}); }

  function initHero(){
    const canvas=$('#dotCanvas'); if(!canvas)return; const ctx=canvas.getContext('2d'); let w=0,h=0,dpr=1,pts=[],mx=-9999,my=-9999;
    function build(){
      const r=canvas.getBoundingClientRect(); dpr=Math.min(devicePixelRatio||1,2); w=Math.max(1,Math.floor(r.width));h=Math.max(1,Math.floor(r.height));canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);
      const off=document.createElement('canvas'), o=off.getContext('2d'); off.width=w;off.height=h; o.fillStyle='#fff'; const fs=Math.min(w*.19,h*.34); o.font=`800 ${fs}px Manrope, sans-serif`;o.textAlign='center';o.textBaseline='middle';o.letterSpacing='-5px'; o.fillText('VIRAJ',w/2,h*.34);o.fillText('GANDHI',w/2,h*.68); const data=o.getImageData(0,0,w,h).data; const step=w<650?7:8; pts=[]; for(let yy=0;yy<h;yy+=step){for(let xx=0;xx<w;xx+=step){if(data[(yy*w+xx)*4+3]>80)pts.push({x:xx,y:yy});}}
    }
    function draw(){ ctx.clearRect(0,0,w,h); for(const p of pts){let x=p.x,y=p.y;const dx=x-mx,dy=y-my,dist=Math.hypot(dx,dy);if(dist<90){const f=(90-dist)/90*19;x+=dx/(dist||1)*f;y+=dy/(dist||1)*f;} const g=ctx.createRadialGradient(x,y,0,x,y,4);g.addColorStop(0,'rgba(130,196,255,.96)');g.addColorStop(1,'rgba(50,116,255,.08)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,2.05,0,Math.PI*2);ctx.fill();} requestAnimationFrame(draw); }
    canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mx=e.clientX-r.left;my=e.clientY-r.top;});canvas.addEventListener('pointerleave',()=>{mx=my=-9999});window.addEventListener('resize',build);document.fonts?.ready.then(build);build();draw();
  }
  function initReveal(){ const els=$$('.reveal'); if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return;} const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target);}}),{threshold:.12});els.forEach(e=>io.observe(e)); }
  function initModal(){
    const modal=$('#projectModal'), title=$('#modalTitle'), kicker=$('#modalKicker'), desc=$('#modalDesc'), evidence=$('#modalEvidence'), tags=$('#modalTags'), actions=$('#modalActions'); if(!modal)return; let last=null;
    function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';last?.focus?.();}
    function open(key,trigger){const p=PROJECTS[key];if(!p)return;last=trigger;kicker.textContent=p.kicker;title.textContent=p.title;desc.textContent=p.desc;evidence.innerHTML=p.evidence.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');tags.innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('');actions.innerHTML=p.actions.map(([label,url,type])=>`<a class="button ${type==='primary'?'button-primary':'button-ghost'} compact" href="${url}" target="_blank" rel="noreferrer">${label}</a>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('.project-modal-close',modal)?.focus();}
    $$('[data-open-project]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.openProject,b)));$('.project-modal-close')?.addEventListener('click',close);$('#modalCloseSecondary')?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close();});
  }
  function initTabs(){ $$('.game-tab').forEach(btn=>btn.addEventListener('click',()=>{ $$('.game-tab').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-selected',b===btn?'true':'false');}); $$('.game-panel').forEach(p=>p.classList.toggle('active',p.id===`game-${btn.dataset.game}`)); })); }
  function initReaction(){ const box=$('#reactionBox'), start=$('#reactionStart'), text=$('#reactionText'), sub=$('#reactionSub'), best=$('#reactionBest'); if(!box)return; let timer=null,readyAt=0,active=false;let b=getNum('vg2026_reaction_best',0);best.textContent=b?`${b} ms`:'--- ms'; function reset(){clearTimeout(timer);active=false;readyAt=0;box.classList.remove('waiting','ready');text.textContent='PRESS START';sub.textContent='Wait for the signal, then click.';} start.addEventListener('click',()=>{clearTimeout(timer);active=true;readyAt=0;box.classList.remove('ready');box.classList.add('waiting');text.textContent='WAIT...';sub.textContent="Don't click yet.";timer=setTimeout(()=>{readyAt=performance.now();box.classList.remove('waiting');box.classList.add('ready');text.textContent='CLICK!';sub.textContent='Now!';},900+Math.random()*2200);});box.addEventListener('click',()=>{if(!active)return;if(!readyAt){clearTimeout(timer);active=false;box.classList.remove('waiting');text.textContent='TOO EARLY';sub.textContent='Start another round.';return;}const ms=Math.round(performance.now()-readyAt);active=false;box.classList.remove('ready');text.textContent=`${ms} ms`;sub.textContent=ms<250?'Very quick.':ms<350?'Nice reaction.':'Try again.';if(!b||ms<b){b=ms;setNum('vg2026_reaction_best',b);best.textContent=`${b} ms`;}}); }
  function initSnake(){ const c=$('#snakeCanvas'), start=$('#snakeStart'), scoreEl=$('#snakeScore'),bestEl=$('#snakeBest');if(!c)return;const x=c.getContext('2d'),cells=20;let snake=[],dir={x:1,y:0},next=dir,food={x:10,y:10},loop=null,score=0,best=getNum('vg2026_snake_best',0);bestEl.textContent=best; function spawn(){do{food={x:Math.floor(Math.random()*cells),y:Math.floor(Math.random()*cells)}}while(snake.some(s=>s.x===food.x&&s.y===food.y));} function draw(){const s=c.width/cells;x.fillStyle='#06101d';x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(100,145,205,.06)';for(let i=0;i<=cells;i++){x.beginPath();x.moveTo(i*s,0);x.lineTo(i*s,c.height);x.stroke();x.beginPath();x.moveTo(0,i*s);x.lineTo(c.width,i*s);x.stroke();}x.fillStyle='#69d7ff';snake.forEach((p,i)=>x.fillRect(p.x*s+2,p.y*s+2,s-4,s-4));x.fillStyle='#67e8a5';x.beginPath();x.arc(food.x*s+s/2,food.y*s+s/2,s*.3,0,Math.PI*2);x.fill();} function end(){clearInterval(loop);loop=null;if(score>best){best=score;setNum('vg2026_snake_best',best);bestEl.textContent=best;}} function step(){dir=next;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.y<0||h.x>=cells||h.y>=cells||snake.some(p=>p.x===h.x&&p.y===h.y)){end();return;}snake.unshift(h);if(h.x===food.x&&h.y===food.y){score++;scoreEl.textContent=score;spawn();}else snake.pop();draw();} function run(){clearInterval(loop);snake=[{x:6,y:10},{x:5,y:10},{x:4,y:10}];dir=next={x:1,y:0};score=0;scoreEl.textContent=0;spawn();draw();loop=setInterval(step,110);} function change(d){const m={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[d];if(!m)return;if(m.x!==-dir.x||m.y!==-dir.y)next=m;}document.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};if(map[e.key]){e.preventDefault();change(map[e.key]);}});$$('[data-dir]').forEach(b=>b.addEventListener('click',()=>change(b.dataset.dir)));start.addEventListener('click',run);run();end();draw(); }
  function initSql(){ const wrap=$('#sqlQuiz'),prog=$('#sqlProgress'),bestEl=$('#sqlBest'),restart=$('#sqlRestart');if(!wrap)return;const qs=[{c:'SELECT * FROM customers WHERE Country = \'NZ\';',q:'Which clause filters rows?',a:['SELECT','WHERE','FROM','ORDER BY'],ok:1},{c:'SELECT Country, COUNT(*) FROM customers GROUP BY Country;',q:'What does GROUP BY do here?',a:['Deletes duplicates','Creates country groups for the aggregate','Sorts countries','Changes the table'],ok:1},{c:'SELECT * FROM invoices WHERE BillingState IS NULL;',q:'What does IS NULL check?',a:['Zero values','Empty strings only','Missing / NULL values','False values'],ok:2},{c:'SELECT c.Name, i.Total FROM customers c JOIN invoices i ON c.CustomerId=i.CustomerId;',q:'Why is the JOIN used?',a:['To combine related rows from two tables','To rename a table','To delete duplicate columns','To make a new database'],ok:0},{c:'HAVING COUNT(*) > 3',q:'When is HAVING especially useful?',a:['Filtering grouped/aggregate results','Choosing columns','Creating a table','Changing a primary key'],ok:0}];let i=0,score=0,best=getNum('vg2026_sql_best',0);bestEl.textContent=`${best}/5`;function render(){const q=qs[i];prog.textContent=`Question ${i+1} of ${qs.length}`;wrap.innerHTML=`<div class="sql-question"><code>${q.c}</code><h4>${q.q}</h4><div class="sql-answers">${q.a.map((a,n)=>`<button class="sql-answer" data-a="${n}">${a}</button>`).join('')}</div></div>`;$$('.sql-answer',wrap).forEach(b=>b.addEventListener('click',()=>choose(Number(b.dataset.a),b)));}function choose(n,b){$$('.sql-answer',wrap).forEach(x=>x.disabled=true);const ok=qs[i].ok;if(n===ok){score++;b.classList.add('correct')}else{b.classList.add('wrong');$$('.sql-answer',wrap)[ok].classList.add('correct')}setTimeout(()=>{i++;if(i>=qs.length){if(score>best){best=score;setNum('vg2026_sql_best',best);bestEl.textContent=`${best}/5`;}wrap.innerHTML=`<div class="sql-question"><h4>You scored ${score}/5</h4><p>Small quiz, real database fundamentals.</p></div>`;prog.textContent='Complete';}else render();},650);}restart.addEventListener('click',()=>{i=0;score=0;render();});render(); }
  function init(){initClock();initCursor();initHero();initReveal();initModal();initTabs();initReaction();initSnake();initSql();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
